# Generated by Django 4.2.4 on 2024-09-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='set',
            new_name='series',
        ),
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(default='No Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default=1, upload_to='cards/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Reverse Foil', 'Reverse Foil'), ('Foil', 'Foil'), ('Rare', 'Rare'), ('PSA', 'PSA')], max_length=20),
        ),
    ]
