# Generated by Django 4.1.1 on 2024-09-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_card_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='grade',
            field=models.CharField(choices=[('Not Graded', 'Not Graded'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
