# Generated by Django 4.2.4 on 2024-09-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_remove_cart_user_cart_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_filename',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
