# Generated by Django 4.2.4 on 2024-09-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_card_image_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
    ]
