# Generated by Django 4.2.4 on 2024-09-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_remove_card_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default=0, upload_to='cards/'),
            preserve_default=False,
        ),
    ]
