# Generated by Django 4.1.1 on 2024-09-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_remove_card_image_cardimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
